# apollo配置
#app:
#  id: coreSystem
#apollo:
#  meta: http://meta-tapollo01cn.svc.monix.tech:8080
kafka-canal:
  consumer:
    properties:
      bootstrap-servers: 10.164.206.130:9092,10.164.206.131:9092
      group-id: core-system-event
      enable-auto-commit: false
      auto-commit-interval-ms: 1000
      session-timeout-ms: 15000
      auto-offset-reset: earliest
      max-poll-records: 20
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  container:
    topics:
      - abakuscom01
    ackMode: MANUAL
datasource:
  hikari:
    - pool-name: glloans_haierdb
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.164.204.101:3306/glloans_haierdb
      password: glloans_123
      username: glloans_haier
      connection-test-query: SELECT 1
      validation-timeout: 18800
      maximum-pool-size: 100
      # 该数据源所包含的数据库
      all-dbs: [glloans_haierdb]
    - pool-name: master
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.164.204.101:3306/glloans_haierdb
      password: glloans_123
      username: glloans_haier
      connection-test-query: SELECT 1
      validation-timeout: 18800
      maximum-pool-size: 100
      all-dbs: [glloans_haierdb]
rocket-mq:
  # 生产者配置
  producer:
    is-on-off: true
    producer-group: core-system-event
    namesrv-addr:  10.164.200.204:9876
    max-message-size: 10240
    send-message-timeout: 1000
    retry-times-when-send-failed: 3
  # 消费者配置
  consumer:
    is-on-off: true
    consumer-group: core-system-event
    namesrv-addr: 10.164.200.204:9876
    topics:
      - topic: core-system
        tags: [core-event]
    consume-thread-min: 15
    consume-thread-max: 40
    consume-message-batch-max-size: 1
spring:
  #  rabbitmq:
  #    virtual-host:
  #    username:
  #    password:
  #    port:
  #    host:
  #    listener:
  #      simple:
  #        prefetch: 1
  #        concurrency: 5
  #        max-concurrency: 10
  data:
    mongodb:
      uri: mongodb://root:Abakus123456@10.164.200.204:22001/admin

redis:
  config:
    host: 10.164.200.204
    port: 6379
    password: Abakus123456
    database-index: 1
    max-active: 8
    max-wait: 20000
    max-idle: 8
    min-idle: 1
    timeout: 50000
    ssl: false
