spring:
#  data:
#    mongodb:
#      uri: mongodb://root:58603924715@127.0.0.1:27017/admin
#  redis:
#    port: 6380
#    password: 58603924715
#    lettuce:
#      pool:
#        max-idle: 8
#        min-idle: 1
#        max-active: 10
#    host: 127.0.0.1
  h2:
    console:
      enabled: true
multi-data-source:
  data-source:
    hikari:
      - pool-name: master
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:data;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
        connection-test-query: SELECT 1
        validation-timeout: 18800
      - pool-name: op_log
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:op_log_db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
        connection-test-query: SELECT 1
        validation-timeout: 18800
#        connection-init-sql: "
#          CREATE TABLE purchase_log (
#              id INT PRIMARY KEY AUTO_INCREMENT COMMENT 'id主键',
#              book_id INT NOT NULL COMMENT '书籍名称',
#              customer_id INT NOT NULL COMMENT '用户id',
#              book_name VARCHAR(128) NOT NULL COMMENT '书籍名称',
#              customer_account_name VARCHAR(64) NOT NULL COMMENT '购买时的账户名',
#              count INT NOT NULL COMMENT '数量',
#              should_amount DECIMAL NOT NULL COMMENT '应付金额',
#              paid_amount DECIMAL NOT NULL COMMENT '实付金额',
#              create_time DATETIME NOT NULL COMMENT '创建时间'
#          );
#        "
      - pool-name: origin
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:origin_db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
        connection-test-query: SELECT 1
        validation-timeout: 18800
#        connection-init-sql: "
#          CREATE TABLE origin_order(
#              id INT PRIMARY KEY AUTO_INCREMENT ,
#              customer_id INT NOT NULL ,
#              count INT NOT NULL ,
#              amount DECIMAL NOT NULL ,
#              pay_time DATETIME NOT NULL,
#              create_time DATETIME NOT NULL,
#              outer_create_time DATETIME
#          )
#        "
    init-sql-script:
      master: classpath:h2/init_schema_business_db.sql
      op_log: classpath:h2/init_schema_op_log_db.sql
      origin: classpath:h2/init_schema_origin_db.sql